version = 1

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "alpine/Dockerfile",
    "ci-deploy-alpine/Dockerfile",
    "elixir-phx/Dockerfile",
    "elixir-phx-mysql/Dockerfile",
    "fpm-nginx/Dockerfile",
    "laravel-php71/Dockerfile",
    "laravel-php72/Dockerfile",
    "laravel-php73/Dockerfile"
  ]

  trusted_registries = [
    "docker.io"
  ]
